---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-crd-gcore-sfs-controller-io-v1-nfsprovisioner
  failurePolicy: Fail
  name: mnfsprovisioner.kb.io
  rules:
  - apiGroups:
    - crd.gcore-sfs-controller.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nfsprovisioners
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-crd-gcore-sfs-controller-io-v1-nfsprovisioner
  failurePolicy: Fail
  name: vnfsprovisioner.kb.io
  rules:
  - apiGroups:
    - crd.gcore-sfs-controller.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nfsprovisioners
  sideEffects: None
