# permissions for end users to view nfsprovisioners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nfsprovisioner-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gcore-sfs-controller
    app.kubernetes.io/part-of: gcore-sfs-controller
    app.kubernetes.io/managed-by: kustomize
  name: nfsprovisioner-viewer-role
rules:
- apiGroups:
  - crd.gcore-sfs-controller.io
  resources:
  - nfsprovisioners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.gcore-sfs-controller.io
  resources:
  - nfsprovisioners/status
  verbs:
  - get
